---
- name: update (RH)
  hosts: [webserver], [nfs], [db]
  become: true
  become_user: root
  tasks:
    - name: install wire shark
      yum:
        name: wireshark
        state: present
    
    - name: update rh severs
      yum:
        update_cache: yes

