[nfs]
172.31.90.65 ansible_ssh_user='ec2-user'

[webservers]
172.31.90.160 ansible_ssh_user='ec2-user'
172.31.84.204 ansible_ssh_user='ec2-user'

[db]
172.31.92.17 ansible_ssh_user='ec2-user' 

[lb]
172.31.84.112 ansible_ssh_user='ubuntu'